config/routes.rb
Rails.application.routes.draw do
  
  get 'user_show/show'
  resources :tasks do
    member do
      get 'approve'
      get 'reject'
    end
    resources :comments, only: [:index,:new, :create, :destroy, :edit, :update]
  end

  root to: "home#index" 

 resources :user_show, only: [:show]

  devise_for :users
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  validates :content , presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_task
  before_action :set_comment, only: [ :edit, :update, :destroy]
  before_action :authorize_comment_access, only: [:edit, :update]

  def index
    @comments = @task.comments
  end

  def new
    @comment = @task.comments.build 
    respond_to do |format|
      format.js #new.js.erb
    end
  end

  def create
    @comment = @task.comments.build(comment_params)
    @comment.user = current_user
    
    if @comment.save
      redirect_to task_path(@task), notice: 'Comment created successfully.'
    else
      render :new
    end
  end

  def edit
   
  end

  def update
    if @comment.update(comment_params)
      redirect_to task_path(@task), notice: 'Comment updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to task_path(@task), notice: 'Comment deleted successfully.'
  end

  private

  def set_task
    @task = Task.find(params[:task_id])
  end

  def set_comment
    @comment = @task.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content, :created_at)
  end
  
  def authorize_comment_access
    unless @comment.user_id == current_user&.id
      redirect_to root_path, alert: 'You are not authorized to access this comment.'
    end
  end 

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<h4>New Comment</h4>

<%= form_with(model: [@task, @comment], url: task_comments_path(@task), method: :post) do |form| %>

  <%= form.label :content, 'Content' %>
  <%= form.text_area :content%>

  <%= form.submit 'Create Comment', class: 'btn btn-primary' %>
<% end %>

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>

<%= form_with(model: [@task, @comment], url: task_comment_path(@task, @comment), method: :patch) do |f| %>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit "Update Comment" %>
  </div>
<% end %>

app/views/comments/new.html.erb
<!-- app/views/comments/new.html.erb -->
<h1>New Comment</h1>

<%= form_with(model: [@task, @comment], url: task_comments_path(@task), method: :post) do |form| %>

  <%= form.label :content, 'Content' %>
  <%= form.text_area :content%>

  <%= form.submit 'Create Comment', class: 'btn btn-primary' %>
<% end %>
  

app/views/comments/new.js.erb
<%# views/comments/new.js.erb %>

document.getElementById("comments-container").innerHTML = "<%= j  render 'form' %>";