config/routes.rb
Rails.application.routes.draw do
  
  get 'user_show/show'
  resources :tasks do
    member do
      get 'approve'
      get 'reject'
    end
    resources :comments, only: [:index,:new, :create, :destroy, :edit, :update]
  end

  root to: "home#index" 

 resources :user_show, only: [:show]

  devise_for :users
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :assignee, class_name: 'User'
    belongs_to :approver, class_name: 'User'
    belongs_to :organization
    has_many :comments, as: :commentable, dependent: :destroy

    validates :name, presence: true
    validates :description, presence: true
    validates :start_date, presence: true
    validates :end_date, presence: true
    validate :validate_dates
  

    enum status: {
      todo: 'ToDo',
      in_progress: 'In Progress',
      in_review: 'In Review',
      approved: 'Approved',
      rejected: 'Rejected',
      closed: 'Closed'
    }
    
    after_update :send_assignment_notification, if: :saved_change_to_assignee_id?
    after_update :send_approval_notification, if: :saved_change_to_approver_id?

  

  def send_assignment_notification
    NotificationMailer.assignment_notification(self).deliver_now
  end

  def send_approval_notification
    NotificationMailer.approval_notification(self).deliver_now
  end

    private

    # validate :validate_assignee_not_organization_admin
    # validate :validate_approver_not_organization_admin
    # def validate_assignee_not_organization_admin
    #   if assignee&.organization_admin?
    #     errors.add(:assignee_id, 'cannot be an organization admin')
    #   end
    # end

    def validate_dates
      if end_date < start_date
        errors.add(:end_date, 'is not less than start_date')
      end
    end

    # def validate_approver_not_organization_admin
    #   if approver&.organization_admin?
    #     errors.add(:approver_id, ' cannot be an organization admin')
    #   end
    # end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :authenticate_user!
  before_action :set_current_organization
  before_action :set_task, only: [:show, :destroy, :edit, :update]
  before_action :check_admin_role, only: [:create, :destroy, :new]
  before_action :authorize_task_access, only: [:show, :edit, :update]

  def index
    @tasks = @current_organization.tasks
    filter_tasks
    sort_tasks
    search_tasks
  end


  def new
    @task = @current_organization.tasks.new
    @task.status = 'ToDo'
  end

  def create
    @task = @current_organization.tasks.new(task_params)
    @task.status = 'ToDo'
    if @task.save
      redirect_to @task, notice: 'Task created successfully.'
    else  
      render :new
    end
  end

  def edit
    @task = @current_organization.tasks.find(params[:id])
    @assignees = @current_organization.users.where.not(role: 'organization_admin')

    if  @task.assignee == @task.approver 
      @status_options = Task.statuses.slice(:in_progress, :in_review, :approved, :rejected).keys
    elsif current_user.organization_admin? && @task.assignee == current_user
      @status_options = Task.statuses.slice(:in_progress, :in_review, :todo, :closed).keys
    elsif  current_user.organization_admin? && @task.approver == current_user 
      @status_options = Task.statuses.slice(:approved, :rejected, :todo, :closed).keys
    else
      if @task.assignee == current_user
        @status_options = Task.statuses.slice(:in_progress, :in_review).keys
      elsif @task.approver == current_user  && (@task.status == 'in_review')
        @status_options = Task.statuses.slice(:approved, :rejected).keys
      elsif current_user.organization_admin?  && (@task.status == 'approved' || @task.status == 'rejected')
        @status_options = Task.statuses.slice(:todo, :closed).keys
      else
        @status_options = []
      end
    end
  end

  def update
    if @task.update(task_params)
      redirect_to @task, notice: 'Task updated successfully.'
    else
      redirect_to @task, alert: 'Failed to update the task.'
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: 'Task deleted successfully.'
  end

  def show
  end

  private

  def set_current_organization
    @organizations = current_user.organizations
    @current_organization = current_user.current_organization || @organizations.first
  end

  def set_task
    @task = @current_organization.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :description, :assignee_id, :approver_id, :status, :start_date, :end_date, :repeat_task, :frequency, :due_date)
  end

  def filter_tasks
    if params[:name].present?
      @tasks = @tasks.where(name: params[:name])
    end
  
    if params[:status].present?
      @tasks = @tasks.where(status: params[:status])
    end 
  
    if params[:assignee].present?
      @tasks = @tasks.joins(:assignee).where(users: { name: params[:assignee] })
    end
  
    if params[:approver].present?
      @tasks = @tasks.joins(:approver).where(users: { name: params[:approver] })
    end
  
    if params[:frequency].present?
      @tasks = @tasks.where(frequency: params[:frequency])
    end
  end

  def sort_tasks
    sort_field = params[:sort_field]
    sort_direction = params[:sort_direction]

    if sort_field.present? && sort_direction.present?
      case sort_field
      when 'name'
        @tasks = @tasks.order(name: sort_direction)
      when 'assignee'
        @tasks = @tasks.joins(:assignee).order('users.name ' + sort_direction)
      when 'approver'
        @tasks = @tasks.joins(:approver).order('users.name ' + sort_direction)
      when 'status'
        @tasks = @tasks.order(status: sort_direction)
      when 'start_date'
        @tasks = @tasks.order(start_date: sort_direction)
      when 'end_date'
        @tasks = @tasks.order(end_date: sort_direction)
      when 'frequency'
        @tasks = @tasks.order(frequency: sort_direction)
      when 'due_date'
        @tasks = @tasks.order(due_date: sort_direction)
      end
    end
  end

  def search_tasks
    if params[:search].present?
      search_query = params[:search].strip.downcase
      @tasks = @tasks.where("lower(name) LIKE :search OR lower(description) LIKE :search", search: "%#{search_query}%") 
    end
  end

  def check_admin_role
    unless current_user.organization_admin?
      redirect_to root_url, alert: 'You are not authorized to perform this action.'
    end
  end

  def authorize_task_access
    super(@task)
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_filter.html.erb
<table class="table table-info">
  <%= form_tag(tasks_path, method: "get") do %>
    <tr>
      <th>
        <div class="field">
          <%= label_tag :name, "Task" %>
          <%= select_tag :name, options_for_select(Task.where(organization_id: current_user.current_organization_id).pluck(:name).uniq, params[:name]), include_blank: true %>
        </div>
      </th>
      <th>
        <div class="field">
          <%= label_tag :status, "Status" %>
          <%= select_tag :status, options_for_select(Task.where(organization_id: current_user.current_organization_id).pluck(:status).uniq, params[:status]), include_blank: true %>
        </div>
      </th>
      <th>
        <div class="field">
          <%= label_tag :assignee, "Assignee" %>
          <%= select_tag :assignee, options_for_select(User.joins(:user_organizations).where(user_organizations: { organization_id: current_user.current_organization_id }).pluck(:name).uniq, params[:assignee]), include_blank: true %>
        </div>
      </th>
      <th>
        <div class="field">
          <%= label_tag :approver, "Approver" %>
          <%= select_tag :approver, options_for_select(User.joins(:user_organizations).where(user_organizations: { organization_id: current_user.current_organization_id }).pluck(:name).uniq, params[:approver]), include_blank: true %>
        </div>
      </th>
      <th>
        <div class="field">
          <%= label_tag :frequency, "Frequency" %>
          <%= select_tag :frequency, options_for_select(Task.where(organization_id: current_user.current_organization_id).pluck(:frequency).uniq, params[:frequency]), include_blank: true %>
        </div>
      </th>
      <th>
        <div class="actions">
          <%= submit_tag "Filter" %>
        </div>
      </th>
      <th>
        <div class="actions">
          <%= text_field_tag(:search, params[:search], placeholder: "Search tasks") %>
          <%= submit_tag("Search", class: "search-button") %>
        </div>
      </th>
      <th>
        <div class="actions">
          <%= link_to "Clear", tasks_path %>
        </div>
      </th>
    </tr>
  <% end %>
</table>

app/views/tasks/_form.html.erb
<html oncontextmenu="return false">
<%= form_with(model: task, local: true) do |form| %>

  <% if task.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h4>
      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %> 


  <div class="mb-3">
    <%= form.label :Title, class: 'form-label' %>
    <%= form.text_field :name,disabled: !current_user.organization_admin?,id: 'txt', class: 'form-control form-control' %>
  </div>

   <div class="mb-3">
    <%= form.label :Description, class: 'form-label' %>
    <%= form.text_field :description,disabled: !current_user.organization_admin?,id: 'txt', class: 'form-control form-control' %>
     <%# <%= form.label :description, @task.description %>
  </div>

  <% if current_user.organization_admin? %>

  <div class="mb-3">
    <%= form.label :assignee_id, class: 'form-label' %>
    <%= form.collection_select :assignee_id,@current_organization.users, :id, :name, { prompt: true }, { class: 'form-control form-control-sm' }  %>
  </div>

  <div class="mb-3">
    <%= form.label :approver_id, class: 'form-label' %>
    <%= form.collection_select :approver_id, @current_organization.users, :id, :name, { prompt: true }, { class: 'form-control form-control-sm' } %>
  </div>  

  <div class="mb-3">
    <%= form.label :start_date, class: 'form-label' %>
    <%= form.date_field :start_date, {class: 'form-control form-control'} %>
  </div>

  <div class="mb-3">
    <%= form.label :end_date, class: 'form-label' %>
    <%= form.date_field :end_date, {class: 'form-control form-control'} %>
  </div>
  
  <div  class="mb-3 form-check">
    <%= form.check_box :repeat_task, {class: 'class="form-check-input', id: 'mycheckbox' }%>
    <%= form.label :reapeat_task, class: 'form-check-label' %>
  </div>

  <div   id='mycheckboxdiv' style="display: none;">
    <div class="mb-3">
      <%= form.label :frequency, class: 'form-label' %>
      <%= form.select :frequency,['daily', 'weekly','monthly','yearly'], {prompt: true},{class: 'form-control form-control-sm'} %>
    </div>  

    <div class="mb-3">
      <%= form.label :due_date, class: 'form-label' %>
      <%= form.date_field :due_date, {class: 'form-control form-control', min: Date.current} %>
    </div>
  </div>

  <% end %>

  <div class="mb-3">
    <%= form.label :status, class: 'form-label'%>
    <% if @status_options.present? %>
      <%= form.select :status, options_for_select(@status_options), {prompt: true}, {class: 'form-select'} %>
    <% else %>  
     <h3><%=form.text_field :status, class: 'form-control',  disabled: true%></h3>
    <% end %>
  </div><br>

  <div class="mb-3">
    <%= form.submit %>
  </div>
<% end %>
</html>

<script>
  document.addEventListener('contextmenu', event => event.preventDefault()); 
</script>



<script>
  document.addEventListener('DOMContentLoaded', function() {
    var mycheckbox = document.getElementById('mycheckbox');
    var mycheckboxdiv = document.getElementById('mycheckboxdiv');
    function toggleDivVisibility() {
      mycheckboxdiv.style.display = mycheckbox.checked ? 'block' : 'none';
    }
    mycheckbox.addEventListener('change', toggleDivVisibility);
    toggleDivVisibility();
  });
</script>

app/views/tasks/edit.html.erb
<h2>Edit Task</h2>

<%= render 'form', task: @task %>
<br>
<h3 class="col-11"><strong><%= link_to 'Back', tasks_path %></strong></h3>

app/views/tasks/index.html.erb
<%= render "filter"%>

<h2>Task List</h2>
 
  <table class="table table-info table-striped">
      <tr>
        <th>
          <%= link_to 'Task Name', tasks_path(sort_field: 'name', sort_direction: params[:sort_field] == 'name' && params[:sort_direction] == 'asc' ? 'desc' : 'asc') %>
        </th>
        <th>Description</th>
        <th>
          <%= link_to 'Status', tasks_path(sort_field: 'status', sort_direction: params[:sort_field] == 'status' && params[:sort_direction] == 'asc' ? 'desc' : 'asc') %>
        </th>
        <th>
          <%= link_to 'Assignee', tasks_path(sort_field: 'assignee', sort_direction: params[:sort_field] == 'assignee' && params[:sort_direction] == 'asc' ? 'desc' : 'asc') %>
        </th>
        <th>
          <%= link_to 'Approver', tasks_path(sort_field: 'approver', sort_direction: params[:sort_field] == 'approver' && params[:sort_direction] == 'asc' ? 'desc' : 'asc') %>
        </th>
        <th>
          <%= link_to 'Start Date', tasks_path(sort_field: 'start_date', sort_direction: params[:sort_field] == 'start_date' && params[:sort_direction] == 'asc' ? 'desc' : 'asc') %>
        </th>
        <th>
          <%= link_to 'End Date', tasks_path(sort_field: 'end_date', sort_direction: params[:sort_field] == 'end_date' && params[:sort_direction] == 'asc' ? 'desc' : 'asc') %>
        </th>
        <th>Repeat Task</th>
        <th>
          <%= link_to 'Frequency', tasks_path(sort_field: 'frequency', sort_direction: params[:sort_field] == 'frequency' && params[:sort_direction] == 'asc' ? 'desc' : 'asc') %>
        </th>
        <th>
          <%= link_to 'Due Date', tasks_path(sort_field: 'due_date', sort_direction: params[:sort_field] == 'due_date' && params[:sort_direction] == 'asc' ? 'desc' : 'asc') %>
        </th>
        <th>Actions</th>
      </tr>
    <tbody>
      <% @tasks.each do |task| %>
        <% if task.assignee == current_user || task.approver == current_user || current_user.organization_admin? %>
          <tr>
            <td><%= task.name %></td>
            <td><%= task.description %></td>
            <td><%= task.status %></td>
            <td><%= task.assignee.name %></td>
            <td><%= task.approver.name %></td>
            <td><%= task.start_date %></td>
            <td><%= task.end_date %></td>
            <td><%= task.repeat_task %></td>
            <td><%= task.frequency %></td>
            <td><%= task.due_date %></td>
            <td>
              <%= link_to 'Show', task %>
              <% if task.assignee == current_user || task.approver == current_user || current_user.organization_admin? %>
                <%= link_to 'Edit', edit_task_path(task) %>
                <%= link_to 'Delete', task_path(task), method: :delete, data: { confirm: 'Are you sure you want to delete this task?' } %>
              <% end %>
              <%= link_to 'Add Comment', new_task_comment_path(task), id: 'add-comment-link', remote: true %>
            </td>
          </tr>
        <% end%>
      <% end %>
    </tbody>
  </table>


<div id="comments-container"> </div>

<%= javascript_include_tag 'comments' %>

app/views/tasks/new.html.erb
<h2>New Task</h2>

<%= render 'form', task: @task %>
<br>
<h3><strong><%= link_to 'Back', tasks_path %></strong></h3>

app/views/tasks/show.html.erb
<h2>Task Details</h2>

<table  class="table table-info table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>status</th>
      <th>Assignee</th>
      <th>Approver</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Repeat Task</th>
       <% if @task.repeat_task?%>
          <th>Frequency</th>
          <th>Due Date</th>
       <% end %>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= @task.name %></td>
        <td><%= @task.description%></td>
        <td><%= @task.status%></td>
        <td><%= @task.assignee.name %></td>
        <td><%= @task.approver.name %></td>
        <td><%= @task.start_date %></td>
        <td><%= @task.end_date %></td>
        <td><%= @task.repeat_task %></td>
        <% if @task.repeat_task?%>
          <td><%= @task.frequency%></td>
          <td><%= @task.due_date%></td>
        <% end %>
        <td> 
         <% if  @task.assignee == current_user || @task.approver == current_user || current_user.organization_admin?%>
          <%= link_to 'Edit', edit_task_path(@task) %>
          <%= link_to 'Delete', task_path(@task), method: :delete, data: { confirm: 'Are you sure you want to delete this task?' } , disabled: !current_user.organization_admin?%> 
         <% end %>
          <%= link_to 'Back', tasks_path %>
        </td>
    </tr>
  </tbody>
</table>

 <h2>Comments</h2>
  <% @task.comments.each do |comment| %>

    <p><strong><%= comment.user.name %>:</strong> <%= comment.content %> </p>
    <p><%= time_ago_in_words(comment.created_at) %> ago.</p>

    <% if comment.user == current_user %>
      <p><%= link_to 'Edit',   edit_task_comment_path(@task, comment)%> |
      <%= link_to 'Delete', task_comment_path(@task, comment), method: :delete, data: { confirm: 'Are you sure you want to delete this comment?' } %></p>
    <% end %>

  <% end %>

<div>
  <%= link_to 'Add Comment', new_task_comment_path(@task),id: 'add-comment-link', remote: true %> 
</div>

<div id="comments-container"></div>

<%= javascript_include_tag 'comments' %>