config/routes.rb
Rails.application.routes.draw do
  
  get 'user_show/show'
  resources :tasks do
    member do
      get 'approve'
      get 'reject'
    end
    resources :comments, only: [:index,:new, :create, :destroy, :edit, :update]
  end

  root to: "home#index" 

 resources :user_show, only: [:show]

  devise_for :users
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      @organizations = current_user.organizations
      if current_user.organization_admin?
        if params[:organization_id].present?
          @current_organization = @organizations.find(params[:organization_id])
          current_user.current_organization = @current_organization
          current_user.save
        else
          @current_organization = current_user.current_organization || @organizations.first
        end
      else
        @current_organization = current_user.organizations #organization
      end
        @current_organization = current_user.current_organization || @organizations.first
        @tasks = @current_organization.tasks
        @users = @current_organization.users
    else
      render ...
    end
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/home/_taskslist.html.erb
<h3>Task List</h3>

<table class="table table-info table-striped" style="width: 80%; margin-left: 5px">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Status</th>
    <th>Assignee</th>
    <th>Approver</th>
    <th>Actions</th>
  </tr>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <% if task.assignee == current_user || task.approver == current_user || current_user.organization_admin? %>
          <td class="table-light"><%= task.name %></td>
          <td class="table-light"><%= task.description %></td>
          <td class="table-light"><%= task.status %></td>
          <td class="table-light"><%= task.assignee.name %></td>
          <td class="table-light"><%= task.approver.name %></td>
          <td class="table-light">
            <%= link_to 'Show', task %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if current_user.organization_admin? %>
  <h3>User List</h3>
  <table class="table table-info table-striped" style="width: 80px; margin-left: 5px">
    <tr>
      <th>User Name</th>
    </tr>
    <tbody>
      <% @users.each do |user| %>
        <% unless user.organization_admin? %>
          <tr>
            <td class="table-light"><%= link_to user.name, user_show_path(user.id, :user => user) %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <% if current_user.organization_admin? %>
    <% if @organizations.size == 1 %>
     <%= link_to @organizations.first.name, root_path(organization_id: @organizations.first.id), class: 'btn btn-info disabled' %><br>
    <% else %>
      <%= form_tag(root_path, method: :get) do %>
        <div class="dropdown">
          <button class="btn btn-info dropdown-toggle" type="button" id="organizationDropdown" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.current_organization ? current_user.current_organization.name : "Select Organization" %>
          </button>
          <ul class="dropdown-menu" aria-labelledby="organizationDropdown">
            <% @organizations.each do |org| %>
              <li>
                <% if current_user.current_organization == org %>
                  <a class="dropdown-item disabled" href="#"><%= org.name %></a>
                <% else %>
                  <%= link_to org.name, root_path(organization_id: org.id), class: 'dropdown-item' %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>
    <% end %>
    <br>
    <h2>Welcome admin <%= current_user.name %></h2>
    <h3>From <%= @current_organization.name %> organization</h3>
    <%= render 'taskslist' %>
  <% else %>
    <h2>Welcome user <%= current_user.name %></h2>
    <h3>From <%= @current_organization.name %> organization</h3>
    <%= render 'taskslist' %>
  <% end %>
<% end %>