config/routes.rb
Rails.application.routes.draw do
  
  get 'user_show/show'
  resources :tasks do
    member do
      get 'approve'
      get 'reject'
    end
    resources :comments, only: [:index,:new, :create, :destroy, :edit, :update]
  end

  root to: "home#index" 

 resources :user_show, only: [:show]

  devise_for :users
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'comments' %>
    <%= javascript_include_tag 'rails-ujs' %>

  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js'%>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css' %>
    

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

 
  </head>

  <body>
    <br>
    <nav class="navbar navbar-expand-md navbar-dark bg-info">
      <h6 class= 'navbar-brand' > Task App</h6>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        <% if user_signed_in? %>
          <% case current_user.role %>
          <% when 'organization_admin' %>
            <li class="nav-item active">
              Welcome admin <br> <p align="center"><strong><%= current_user.name%></strong>
            </li>
             <li class="nav-item active">
              <%= link_to 'New Task', new_task_path, class: 'nav-link' %>
            </li> 
           <% when 'user' %>
            <li class="nav-item active">
               Welcome user <br> <p align="center"><strong><%= current_user.name %></strong></p> 
            </li>
          <% end %>
           <li class="nav-item active">
              <%= link_to 'Tasks', tasks_path, class: 'nav-link' %>
          </li> 
          <li class="nav-item active">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
             Organization <br><p align="center"><strong><%= @current_organization.name %></strong>
          </li>
          <% else%>
          <li class="nav-item active">
             <%= link_to "Sign in", new_user_session_path,  class: 'nav-link' %> 
          </li>
          <% end %>
      </ul> 
    </div>
    </nav>
    <br>
    <% if !flash.empty? %>
      <% if flash.notice %>
        <div class="alert alert-info"> <%= notice %> </div> 
      <% else %>
        <div class="alert alert-danger"> <%= alert %> </div> 
      <% end %>
    <% end %>
    <br><br>
    <%= yield %>
  </body>
</html> 